### ISSUE TITLE
Move auto-processor command functionality into 'commands' submodule

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/auto_process_ngs#266]
Request to move the code for a number of auto-processor commands from the `AutoProcess` class into the `commands` submodule, specifically:

* [x] `make_fastqs` (see PR #215)
* [x] `analyse_barcodes` (see PR #267)
* [x] `merge_fastq_dirs` (see PR #268)
* [x] `import_project` (see PR #274)
* [x] `clone` (see PR #276)
* [x] `setup` (see PR #277)
