### ISSUE TITLE
Switch from [c]StringIO to io.StringIO

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/auto_process_ngs#367]
Switch from `[c]StringIO` to `io.StringIO`, to support Python 2 and 3 - see e.g.:

https://python-future.org/compatible_idioms.html#stringio

Utilities and modules using [c]StringIO (discovered with `find -name "*.py" -exec grep -l cStringIO {} \;`):

- [x] `auto_process_ngs/test/test_applications.py` PR #502
- [x] `auto_process_ngs/test/test_simple_scheduler.py` PR #511
- [x] `auto_process_ngs/test/test_stats.py` PR #512
- [x] `auto_process_ngs/test/test_samplesheet_utils.py` PR #510
- [x] `auto_process_ngs/test/test_config.py` PR #498
- [x] `auto_process_ngs/pipeliner.py` PR #489
